SOURCES=\
viblio_video_analyzer.cpp\
VideoProcessor.cpp

OBJS=$(SOURCES:.cpp=.o)
CFLAGS=-std=c++0x -I../../Libraries
EXECNAME=viblio_video_analyzer

%.o : %.cpp
	g++ -c $(CFLAGS) $< -o $@

$(EXECNAME) : $(OBJS)
	g++ -std=c++0x -o $@ $(OBJS) -L../../Libraries/FileSystem -L../../Libraries/VideoSource -L../../Libraries/Analytics.FaceAnalyzer/ -L../../../../Windows_and_Linux_Common/OpenTLD/src/libopentld/tld/ -L../../../../Windows_and_Linux_Common/OpenTLD/src/3rdparty/cvblobs/ -L../../../../Windows_and_Linux_Common/OpenTLD/src/libopentld/mftracker -lVideoSource -lFaceAnalyzer -lFileSystem -lOpenTld -lopencv_imgproc -lopencv_core -lcvblobs -lmftracker -lopencv_highgui -lopencv_objdetect -lboost_program_options -lboost_system -lboost_filesystem -lopencv_video

clean :
	rm -rf $(EXECNAME) $(OBJS)

